name: deSEC-idontgit
version: '0.1'
summary: Keep your deSEC records up-to-date
description: |
This simple snap updates the configured deSEC domain names every five
minutes. Configure it by providing your token:

    $ snap set deSEC-idontgit password=<secret>

And configure your domain name list (comma-separated, no spaces):

    $ snap set deSEC-idontgit username=domain1.com,domain2.com


grade: draft
confinement: strict

apps:
  desec:
    command: desec
    daemon: simple
    plugs: [network]

parts:
  scripts:
    plugin: dump
    stage-packages: [curl]
