name: desec-idontgit
version: '0.1'
summary: Keep your deSEC records up-to-date
description: This simple snap updates the configured deSEC domain names every five minutes.

grade: draft
confinement: strict

apps:
  desec:
    command: desec
    daemon: simple
    plugs: [network]

parts:
  scripts:
    plugin: dump
    stage-packages: [curl]
